ElementwiseAdd_hls_0:
  PE: 1
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_embedded
  outFIFODepths:
  - 2
  ram_style: auto
ElementwiseAdd_hls_1:
  PE: 1
  inFIFODepths:
  - 256
  - 256
  mem_mode: internal_embedded
  outFIFODepths:
  - 2
  ram_style: auto
ElementwiseAdd_hls_2:
  PE: 1
  inFIFODepths:
  - 256
  - 256
  mem_mode: internal_embedded
  outFIFODepths:
  - 2
  ram_style: auto
ElementwiseMul_hls_0:
  PE: 1
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_embedded
  outFIFODepths:
  - 2
  ram_style: auto
MVAU_hls_0:
  PE: 1
  SIMD: 2
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_decoupled
  outFIFODepths:
  - 2
  ram_style: auto
  ram_style_thresholds: auto
  resType: dsp
  runtime_writeable_weights: 0
MVAU_hls_1:
  PE: 1
  SIMD: 2
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_decoupled
  outFIFODepths:
  - 2
  ram_style: auto
  ram_style_thresholds: auto
  resType: dsp
  runtime_writeable_weights: 0
MVAU_hls_2:
  PE: 1
  SIMD: 2
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_decoupled
  outFIFODepths:
  - 2
  ram_style: auto
  ram_style_thresholds: auto
  resType: dsp
  runtime_writeable_weights: 0
MVAU_hls_3:
  PE: 1
  SIMD: 2
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_decoupled
  outFIFODepths:
  - 2
  ram_style: auto
  ram_style_thresholds: auto
  resType: dsp
  runtime_writeable_weights: 0
MVAU_hls_4:
  PE: 1
  SIMD: 8
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_decoupled
  outFIFODepths:
  - 2
  ram_style: auto
  ram_style_thresholds: auto
  resType: dsp
  runtime_writeable_weights: 0
MVAU_hls_5:
  PE: 1
  SIMD: 8
  inFIFODepths:
  - 2
  - 2
  mem_mode: internal_decoupled
  outFIFODepths:
  - 2
  ram_style: auto
  ram_style_thresholds: auto
  resType: dsp
  runtime_writeable_weights: 0
MergeMultiHeads_hls_0:
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
ReplicateStream_hls_0:
  PE: 1
  inFIFODepths:
  - 2
  outFIFODepths:
  - 256
  - 256
ReplicateStream_hls_1:
  PE: 1
  inFIFODepths:
  - 2
  outFIFODepths:
  - 256
  - 256
  - 256
ReplicateStream_hls_2:
  PE: 1
  inFIFODepths:
  - 2
  outFIFODepths:
  - 256
  - 256
ScaledDotProductAttention_hls_0:
  inFIFODepths:
  - 512
  - 512
  - 512
  - 0
  - 0
  mac_resource: dsp
  outFIFODepths:
  - 2
  ram_style: block
  ram_style_mask: auto
  ram_style_thresholds: block
ScaledDotProductAttention_hls_1:
  inFIFODepths:
  - 512
  - 512
  - 512
  - 0
  - 0
  mac_resource: dsp
  outFIFODepths:
  - 2
  ram_style: block
  ram_style_mask: auto
  ram_style_thresholds: block
SplitMultiHeads_hls_0:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
  - 2
SplitMultiHeads_hls_1:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
  - 2
SplitMultiHeads_hls_2:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
  - 2
Squeeze_hls_0:
  PE: 1
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_0:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_1:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_10:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_11:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_12:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_13:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_14:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_15:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_16:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_2:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_3:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_4:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_5:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_6:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_7:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_8:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingDataWidthConverter_rtl_9:
  inFIFODepths:
  - 2
  outFIFODepths:
  - 2
StreamingFIFO_rtl_0:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_1:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_10:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_11:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_12:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_13:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_14:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_15:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_16:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_17:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_18:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_19:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_2:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_20:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_21:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_22:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_23:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_24:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_25:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_26:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_27:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_28:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_29:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_3:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_30:
  depth: 512
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_31:
  depth: 512
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_32:
  depth: 512
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_33:
  depth: 512
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_34:
  depth: 512
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_35:
  depth: 512
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_36:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_37:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_38:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_39:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_4:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_40:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_41:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_42:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_43:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_44:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_45:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_46:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_47:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_48:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_49:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_5:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_50:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_51:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_52:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_53:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_54:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_55:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_56:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_6:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_7:
  depth: 2
  impl_style: rtl
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: auto
StreamingFIFO_rtl_8:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
StreamingFIFO_rtl_9:
  depth: 256
  impl_style: vivado
  inFIFODepths:
  - 0
  outFIFODepths:
  - 0
  ram_style: block
Thresholding_rtl_0:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_1:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_10:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_2:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_3:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_4:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_5:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_6:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_7:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_8:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Thresholding_rtl_9:
  PE: 1
  depth_trigger_bram: 0
  depth_trigger_uram: 0
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
  runtime_writeable_weights: 0
Unsqueeze_hls_0:
  PE: 1
  inFIFODepths:
  - 2
  - 2
  outFIFODepths:
  - 2
defaults: {}
